insert into category (id, name, status) values (1, 'n/a', false);
insert into category (id, name, status) values (2, 'Public Utilities', true);
insert into category (id, name, status) values (3, 'Technology', false);
insert into category (id, name, status) values (4, 'n/a', false);
insert into category (id, name, status) values (5, 'n/a', true);
insert into category (id, name, status) values (6, 'Public Utilities', false);
insert into category (id, name, status) values (7, 'Health Care', false);
insert into category (id, name, status) values (8, 'Consumer Services', false);
insert into category (id, name, status) values (9, 'Finance', false);
insert into category (id, name, status) values (10, 'Finance', false);
insert into category (id, name, status) values (11, 'Capital Goods', false);
insert into category (id, name, status) values (12, 'Public Utilities', true);
insert into category (id, name, status) values (13, 'Health Care', false);
insert into category (id, name, status) values (14, 'Finance', true);
insert into category (id, name, status) values (15, 'Capital Goods', false);
insert into category (id, name, status) values (16, 'Finance', false);
insert into category (id, name, status) values (17, 'n/a', false);
insert into category (id, name, status) values (18, 'Health Care', true);
insert into category (id, name, status) values (19, 'Health Care', false);
insert into category (id, name, status) values (20, 'Finance', true);
insert into category (id, name, status) values (21, 'Finance', false);
insert into category (id, name, status) values (22, 'Consumer Services', true);
insert into category (id, name, status) values (23, 'n/a', false);
insert into category (id, name, status) values (24, 'Finance', true);
insert into category (id, name, status) values (25, 'Finance', false);
insert into category (id, name, status) values (26, 'n/a', true);
insert into category (id, name, status) values (27, 'Finance', true);
insert into category (id, name, status) values (28, 'n/a', true);
insert into category (id, name, status) values (29, 'Consumer Non-Durables', true);
insert into category (id, name, status) values (30, 'Technology', false);

insert into product (id, name, creation_date, category_id) values (1, 'Lamb - Whole Head Off,nz', '2024-05-29', 1);
insert into product (id, name, creation_date, category_id) values (2, 'Mushroom - Chantrelle, Fresh', '2023-10-26',2);
insert into product (id, name, creation_date, category_id) values (3, 'Flower - Commercial Bronze', '2024-02-06', 3);
insert into product (id, name, creation_date, category_id) values (4, 'Flour - Semolina', '2023-12-11', 4);
insert into product (id, name, creation_date, category_id) values (5, 'Cheese - Ermite Bleu', '2023-11-13', 2);
insert into product (id, name, creation_date, category_id) values (6, 'Dikon', '2023-12-21', 3);
insert into product (id, name, creation_date, category_id) values (7, 'Clams - Bay', '2024-01-31', 5);
insert into product (id, name, creation_date, category_id) values (8, 'Turnip - Mini', '2023-10-04', 6);
insert into product (id, name, creation_date, category_id) values (9, 'Chicken - Soup Base', '2024-02-26', 7);
insert into product (id, name, creation_date, category_id) values (10, 'Cleaner - Lime Away', '2023-06-15', 8);
insert into product (id, name, creation_date, category_id) values (11, 'Wine - Toasted Head', '2023-07-30', 11);
insert into product (id, name, creation_date, category_id) values (12, 'Devonshire Cream', '2023-11-16', 15);
insert into product (id, name, creation_date, category_id) values (13, 'Table Cloth 54x54 White', '2024-04-21', 2);
insert into product (id, name, creation_date, category_id) values (14, 'Lid Tray - 12in Dome', '2024-03-23', 4);
insert into product (id, name, creation_date, category_id) values (15, 'Chocolate - Pistoles, White', '2023-12-25', 6);
insert into product (id, name, creation_date, category_id) values (16, 'Shrimp - Baby, Warm Water', '2023-07-08', 8);
insert into product (id, name, creation_date, category_id) values (17, 'Pastry - French Mini Assorted', '2023-08-14', 10);
insert into product (id, name, creation_date, category_id) values (18, 'Cheese - Goat With Herbs', '2023-09-07', 12);
insert into product (id, name, creation_date, category_id) values (19, 'Apricots - Dried', '2024-01-30', 15);
insert into product (id, name, creation_date, category_id) values (20, 'Pepper - Julienne, Frozen', '2024-01-25', 16);